"""
Available presets:
    Small_Set
    Large_set
    Extra_Large_set
"""

from Small_Set \
    \
    \
    \
    import NUM_HEALTHY, NUM_SICK, NUM_AREAS, ITERATIONS,\
    DURATION_UNTIL_DEATH, INFECTION_RATE, INCUBATION_PERIOD,\
    SYMPTOMLESS_CHANCE, LETHALITY, AVERAGE_HOUSEHOLD, SOCIAL_RATE,\
    SOCIAL_RATE_RANGE, TRAVELLING_PROB, SOCIAL_DISTANCE, SELF_QUARANTINE,\
    NAMES, RECURRENCE_TIME, AVERAGE_IMMUNITY, TOWN_QUARANTINE
